language: android
jdk: oraclejdk7


# Use Container Based
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - API_LEVEL=23
    - ANDROID_EMULATOR_API_LEVEL=23
    - ANDROID_BUILD_TOOLS_VERSION=23.0.3
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_TARGET=android-22
android:
    components:
        - platform-tools
        - tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$API_LEVEL
        - android-$ANDROID_EMULATOR_API_LEVEL

        # Additional components
        # - extra-google-google_play_services
        - extra-android-support
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-$API_LEVEL
        - addon-google_apis-google-$ANDROID_EMULATOR_API_LEVEL

        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        # - sys-img-armeabi-v7a-android-19
        # - sys-img-x86-android-17
        - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_API_LEVEL

before_install:
    - android list targets
    - chmod +x gradlew
    # Create and start emulator
    - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_API_LEVEL --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator

script: ./gradlew connectedAndroidTest

after_success:
    - mv ./app/build/outputs/apk/app-debug.apk ./app/build/outputs/apk/SingBuses-debug.apk
    - ls ./app/build/outputs/apk/

deploy:
    provider: releases
    api_key: $OAUTH_KEY
    file: ./app/build/outputs/apk/SingBuses-debug.apk
    skip_cleanup: true
    on:
        tags: true

notifications:
  irc:
    channels:
      - "chat.freenode.net#itachi1706mc"
      - "irc.esper.net#itachi1706"
    on_success: always
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_subject}"
      - "Build Status : %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
  email:
    recipients:
      - $PRIVATE_EMAIL
    on_success: change # default: change
    on_failure: always # default: always